### PR TITLE
Adding Gamer Guide and Challenges Page

### PR DESCRIPTION
**Pull request by Jchinja**
Adding Gamer Guide and Challenges Page.
image
image

moved terms and conditions, and code of conduct to community page. 
image

Updated nav bar for the moved pages.

image

### CODE REVIEW

**Review by luxaritas — COMMENTED** [review]
Overall looks good. Two comments:
- Instead of hyperlinking the challenge title, could we make the whole card a link (like on the news page - make sure to include the hover animation)
- ToS/EULA really doesn't make sense under community. Can we move that one back to about? Also, honestly not a fan of having the links in the sidebar at all - I want to say we discussed this before, could you check with Sharif to see if he has any ideas of something to do instead?

**Comment by Jchinjm** [comment]
> * ToS/EULA really doesn't make sense under community. Can we move that one back to about? 
Yep
> * Also, honestly not a fan of having the links in the sidebar at all (it doesn't match the sidebar usage anywhere else on the site) - I want to say we discussed this before, could you check with Sharif to see if he has any ideas of something to do instead?

Sharif proposed something like this for the sidebar
```
Questions or comments?
You can contact us in several ways:
- Post a message on the forum [link] to report a bug or provide feedback.
- Join our Discord [link] to collaborate and socialize with other players.
- Email the developer team at support@eternagame.org for account help.
```

**Comment by luxaritas** [comment]
It looks like you moved the CoC instead of the ToS?

**Comment by luxaritas** [comment]
Also note the need for the hyperlink change

**Pull request merged**
