### PR TITLE
Pagination, filters, result count

### LINKED ISSUE #38: Explicit "load more" button on infinite scroll pages
For accessibility and additional signification that this is what's going on

### LINKED ISSUE #120: List count of results in sidebar on list pages
Eg in listing puzzles, labs, etc., it would be great to see how many total results there are for a given set of filters, now that we no longer have pagination

### PR DESCRIPTION
**Pull request by AlexHalb**
Adds an option to use pages or infinite scroll on puzzles. Also adds a switch filter and displays how many results there are for a query.

* Resolves #38
* Resolves #120

### CODE REVIEW

**Comment by luxaritas** [comment]
Looks great, but a couple things that need to be resolved:
- Switching between pagination/scroll should not require reloading the window
- This breaks other gallery pages, eg labs
- This should probably be implemented in the existing pagination component - provide a prop to it that will either show the pagination or use infinite scroll. Then we can enable it for labs, etc

**Comment by AlexHalb** [comment]
Those should all be resolved now.

**Comment by luxaritas** [comment]
More bugs :D
- Using the paginated view, I'm semi-regularly getting an "Avoided redundant navigation to current location" error
- When changing to scroll, I get two spinning loaders, and the previously existing content disappears
- When changing the page, the pagination widget shifts to the left of the screen instead of staying centered while it's loading
- The pagination probably shouldn't be green - way too stark imo. maybe look at some of the blue options

**Comment by luxaritas** [comment]
I think tags were reenabled on too many things - should just be on the puzzle list. I think UID search also needs to get added to the puzzle list as well?

**Pull request merged**
